src/objects/FeeTable__c.object
<CustomObject>
    <fields>
        <fullName>ParentFeeTable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Fee Table</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>FeeTable__c.Name</field>
                <operation>contains</operation>
                <value>Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FeeTable__c</referenceTo>
        <relationshipLabel>Fee Tables</relationshipLabel>
        <relationshipName>FeeTables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SpecificGrade__c</fullName>
        <label>Specific Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fee Table</label>
    <nameField>
        <label>Fee Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FeeTableExtention.cls
public class FeeTableExtention {
	private final sObject mysObject;
	public String selectedOpt {get;set;}
	private String feeTableId;

	public FeeTableExtention(ApexPages.StandardController stdController)
	{
		this.mysObject = (sObject)stdController.getRecord();

	}

	public List<FeeTable__c> getChildList()
	{	List<FeeTable__c> feeTables = new List<FeeTable__c>();
		If (String.isNotBlank(selectedOpt)) {
			String tmp = '\''+ selectedOpt + '\'';
//			String queryString = 'Select Name, specificgrade__c, ParentFeeTable__c, (Select Name, specificgrade__c, ParentFeeTable__c from FeeTables__r) from FeeTable__c WHERE ParentFeeTable__c = ' + tmp;
			String queryString = 'Select Name, specificgrade__c, ParentFeeTable__c from FeeTable__c WHERE ParentFeeTable__c = ' + tmp;
			feeTables = database.query(queryString);

		}
	return feeTables;
	}


	public List<SelectOption> getFeeTableGroup()
	{	List<FeeTable__c> fts = [SELECT Name FROM FeeTable__c WHERE recordtype.name = 'Parent Fee Table'];
		List<SelectOption> options = new List<SelectOption>();
		options.add(new SelectOption('','-- Select One --'));
		for (FeeTable__c ft : fts) {
			options.add(new SelectOption(ft.id, ft.Name));
		}
		return options;
	}

}